name: Arch Linux Multilib
id: arch-multilib
stages:
- id: build
  base: ghcr.io/archlinux/archlinux:multilib-devel
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  runs:
    - pacman -Syu --noconfirm
  entrypoint: ["/etc/init.sh"]
  modules:
    - name: install-yay-deps
      type: shell
      commands:
      - pacman -S --needed git wget base-devel --noconfirm

    - name: install-yay
      type: shell
      source:
        type: tar
        url: https://github.com/Jguer/yay/releases/download/v12.3.5/yay_12.3.5_x86_64.tar.gz
      commands:
      - tar -xf ./yay_12.3.5_x86_64.tar.gz
      - mv ./yay_12.3.5_x86_64/yay /usr/bin/
