name: Arch Linux Multilib
id: arch-multilib
stages:
- id: build
  base: ghcr.io/archlinux/archlinux:multilib-devel
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  runs:
    - pacman -Syu --noconfirm
  entrypoint: ["/etc/init.sh"]
  modules:
    - name: install-essentials
      type: shell
      commands:
      - pacman -S --needed git wget base-devel --noconfirm
